### ISSUE TITLE
Do numbers of model's quality correspond with new dataset?

### ISSUE THREAD

**Issue by egorsmkv** [kotestyle/g2p_uk#6]
Hello.

I am seeing you uploaded new dataset here - https://github.com/dsakovych/g2p_uk/commit/b34a468634c90afc1b050e89b259485bdd7a07ce

But the numbers in README are still old. Are they the same with that new dataset?

**Comment by dsakovych** [comment]
No, for now there was no time to update model. Maybe in a future, when will get access to my PC. In case of such questions, you can text me directly to telegram, no need to create issue ticket :-)
